sudo: required
language: crystal

addons:
  # Add RethinkDB
  rethinkdb: '2.3'

before_install:
  # Add elasticsearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.1-amd64.deb && \
  sudo dpkg -i --force-confnew elasticsearch-7.0.1-amd64.deb && \
  sudo service elasticsearch restart

install:
  - shards install

before_script:
  - sleep 10

script:
  - crystal spec
  - bin/ameba

