language: crystal
os: linux

services:
  - docker

before_install:
  # Add elasticsearch 7.6
  - docker run --net="host" -p "9300:9300" -p "9200:9200" -e discovery.type=single-node -d blacktop/elasticsearch:7.6
  # Add rethinkdb 2.4
  - docker run --net="host" -p "29015:29015" -p "28015:28015" -d rethinkdb:2.4

install:
  - shards install

before_script:
  - sleep 5

script:
  - crystal spec -v
  - bin/ameba
